spring.application.name=threshold-clinic-project

spring.datasource.url=jdbc:postgresql://localhost:5432/threshold_clinic_intake_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

jwt.EXPIRATION=8640000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarvesh.wani@coditas.com
spring.mail.password=csgramsvidlwxwfq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


file.upload-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

