spring.application.name=threshold-clinic-project

spring.datasource.url=jdbc:postgresql://localhost:5432/threshold_clinic_intake_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

jwt.SECRET="Coditas@12093!18203@91823#09128$30298%30123^76543&12145*12245"
jwt.EXPIRATION=8640000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarvesh.wani@coditas.com
spring.mail.password=csgramsvidlwxwfq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


file.upload-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
