spring.application.name=threshold-clinic-project

spring.datasource.url=jdbc:postgresql://localhost:5432/threshold_clinic_intake_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none